export const GETHOME = 'GETHOME'
export const CHANGEBUYCOUNT = 'CHANGEBUYCOUNT'

//shopcart
export const SHOPCART = 'SHOPCART'
export const TOGGLESHOP = 'TOGGLESHOP'
export const TOGGLEGOOD = 'TOGGLEGOOD'
export const ONECHECKEDSHOP = 'ONECHECKEDSHOP'
export const CHECKEDALLSHOP = 'CHECKEDALLSHOP'
export const TOGGLESTATUS = 'TOGGLESTATUS'
export const DELETEGOOD = 'DELETEGOOD'
export const DELETEMOREGOOD = 'DELETEMOREGOOD'

//分类
export const CATEGORY = 'CATEGORY'
export const ADDSHOPCART = 'ADDSHOPCART'